import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "../../component/navbar";
import Head from "next/head";
import Footer from "../../component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <div className="app-main-container" style={{backgroundColor:"#F1F8FF"}}>
          <div className="main-wrapper" style={{backgroundColor:"#fff"}}>
            <Navbar />
            <div>
            {children}
            </div>
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
